// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/insights/presentation/bloc/insights_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interval/core/errors/failures.dart' as _i6;
import 'package:interval/features/insights/domain/entities/insight.dart' as _i7;
import 'package:interval/features/insights/domain/repositories/insight_repository.dart'
    as _i2;
import 'package:interval/features/insights/domain/usecases/calculate_completion_rate.dart'
    as _i9;
import 'package:interval/features/insights/domain/usecases/generate_daily_insight.dart'
    as _i4;
import 'package:interval/features/insights/domain/usecases/get_top_activities.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInsightRepository_0 extends _i1.SmartFake
    implements _i2.InsightRepository {
  _FakeInsightRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GenerateDailyInsight].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateDailyInsight extends _i1.Mock
    implements _i4.GenerateDailyInsight {
  MockGenerateDailyInsight() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InsightRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInsightRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InsightRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Insight>> call(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [date],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Insight>>.value(
            _FakeEither_1<_i6.Failure, _i7.Insight>(
          this,
          Invocation.method(
            #call,
            [date],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Insight>>);
}

/// A class which mocks [GetTopActivities].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopActivities extends _i1.Mock implements _i8.GetTopActivities {
  MockGetTopActivities() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InsightRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInsightRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InsightRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ActivityCount>>> call(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [date],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.ActivityCount>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.ActivityCount>>(
          this,
          Invocation.method(
            #call,
            [date],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ActivityCount>>>);
}

/// A class which mocks [CalculateCompletionRate].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateCompletionRate extends _i1.Mock
    implements _i9.CalculateCompletionRate {
  MockCalculateCompletionRate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InsightRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeInsightRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.InsightRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, double>> call(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [date],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, double>>.value(
            _FakeEither_1<_i6.Failure, double>(
          this,
          Invocation.method(
            #call,
            [date],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, double>>);
}
