// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/streaks/domain/usecases/update_streak_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interval/core/errors/failures.dart' as _i5;
import 'package:interval/features/streaks/domain/entities/streak.dart' as _i6;
import 'package:interval/features/streaks/domain/repositories/streak_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StreakRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRepository extends _i1.Mock implements _i3.StreakRepository {
  MockStreakRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>> getStreakById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>>.value(
            _FakeEither_0<_i5.Failure, _i6.Streak>(
          this,
          Invocation.method(
            #getStreakById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Streak?>> getActiveStreak(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveStreak,
          [streakType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Streak?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Streak?>(
          this,
          Invocation.method(
            #getActiveStreak,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Streak?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>> getActiveStreaks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveStreaks,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Streak>>(
          this,
          Invocation.method(
            #getActiveStreaks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>> getStreaksByType(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreaksByType,
          [streakType],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Streak>>(
          this,
          Invocation.method(
            #getStreaksByType,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getBestStreakCount(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBestStreakCount,
          [streakType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getBestStreakCount,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getCurrentStreakCount(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentStreakCount,
          [streakType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getCurrentStreakCount,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isStreakActive(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #isStreakActive,
          [streakType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isStreakActive,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>> createStreak({
    required String? streakType,
    required String? startDate,
    int? currentCount = 1,
    int? bestCount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStreak,
          [],
          {
            #streakType: streakType,
            #startDate: startDate,
            #currentCount: currentCount,
            #bestCount: bestCount,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>>.value(
            _FakeEither_0<_i5.Failure, _i6.Streak>(
          this,
          Invocation.method(
            #createStreak,
            [],
            {
              #streakType: streakType,
              #startDate: startDate,
              #currentCount: currentCount,
              #bestCount: bestCount,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Streak>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateStreak(_i6.Streak? streak) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [streak],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateStreak,
            [streak],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> incrementStreak(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementStreak,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #incrementStreak,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> breakStreak(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakStreak,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #breakStreak,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetCurrentCount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCurrentCount,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetCurrentCount,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteStreak(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStreak,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteStreak,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteStreaksByType(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStreaksByType,
          [streakType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteStreaksByType,
            [streakType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>> getAllStreaks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStreaks,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Streak>>(
          this,
          Invocation.method(
            #getAllStreaks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Streak>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i6.Streak?>> watchActiveStreak(
          String? streakType) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActiveStreak,
          [streakType],
        ),
        returnValue: _i4.Stream<_i2.Either<_i5.Failure, _i6.Streak?>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, _i6.Streak?>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Streak>>> watchActiveStreaks() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActiveStreaks,
          [],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Streak>>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Streak>>>);
}
