// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/categories/domain/usecases/get_all_categories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interval/core/errors/failures.dart' as _i5;
import 'package:interval/features/categories/domain/entities/category.dart'
    as _i6;
import 'package:interval/features/categories/domain/repositories/category_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Category>> getCategoryById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Category>>.value(
            _FakeEither_0<_i5.Failure, _i6.Category>(
          this,
          Invocation.method(
            #getCategoryById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Category>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> getAllCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getSystemCategories() => (super.noSuchMethod(
            Invocation.method(
              #getSystemCategories,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getSystemCategories,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> getUserCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCategories,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #getUserCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Category>> createCategory({
    required String? name,
    required List<String>? keywords,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [],
          {
            #name: name,
            #keywords: keywords,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Category>>.value(
            _FakeEither_0<_i5.Failure, _i6.Category>(
          this,
          Invocation.method(
            #createCategory,
            [],
            {
              #name: name,
              #keywords: keywords,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Category>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateCategory(
          _i6.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCategory(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteCategory,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String?>> categorizeContent(
          String? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #categorizeContent,
          [content],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String?>>.value(
            _FakeEither_0<_i5.Failure, String?>(
          this,
          Invocation.method(
            #categorizeContent,
            [content],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getCategoriesCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesCount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getCategoriesCount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Category>>> watchCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchCategories,
          [],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Category>>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Category>>>);
}
