// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/export/domain/usecases/export_to_json_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interval/core/errors/failures.dart' as _i5;
import 'package:interval/features/export/domain/repositories/export_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportRepository extends _i1.Mock implements _i3.ExportRepository {
  MockExportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> exportToCSV({
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToCSV,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #exportToCSV,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> exportToJSON({
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToJSON,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #exportToJSON,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>
      getExportHistory() => (super.noSuchMethod(
            Invocation.method(
              #getExportHistory,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i3.ExportRecord>>(
              this,
              Invocation.method(
                #getExportHistory,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>> getExportsByType(
          String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExportsByType,
          [type],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i3.ExportRecord>>(
          this,
          Invocation.method(
            #getExportsByType,
            [type],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>> getRecentExports(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExports,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i3.ExportRecord>>(
          this,
          Invocation.method(
            #getRecentExports,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i3.ExportRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteOldExports(
          int? olderThanDays) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldExports,
          [olderThanDays],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteOldExports,
            [olderThanDays],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteExport(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExport,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteExport,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalExportedRecords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalExportedRecords,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getTotalExportedRecords,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalExportSize() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalExportSize,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getTotalExportSize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
