// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/export/presentation/bloc/export_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interval/core/errors/failures.dart' as _i6;
import 'package:interval/features/export/domain/repositories/export_repository.dart'
    as _i2;
import 'package:interval/features/export/domain/usecases/export_to_csv.dart'
    as _i4;
import 'package:interval/features/export/domain/usecases/export_to_json.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExportRepository_0 extends _i1.SmartFake
    implements _i2.ExportRepository {
  _FakeExportRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExportToCSV].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportToCSV extends _i1.Mock implements _i4.ExportToCSV {
  MockExportToCSV() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExportRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExportRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ExportRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call({
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [ExportToJSON].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportToJSON extends _i1.Mock implements _i7.ExportToJSON {
  MockExportToJSON() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExportRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeExportRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ExportRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call({
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
