// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/categories/presentation/bloc/categories_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interval/core/errors/failures.dart' as _i6;
import 'package:interval/features/categories/domain/entities/category.dart'
    as _i7;
import 'package:interval/features/categories/domain/repositories/category_repository.dart'
    as _i2;
import 'package:interval/features/categories/domain/usecases/create_category.dart'
    as _i8;
import 'package:interval/features/categories/domain/usecases/delete_category.dart'
    as _i10;
import 'package:interval/features/categories/domain/usecases/get_all_categories.dart'
    as _i4;
import 'package:interval/features/categories/domain/usecases/update_category.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategories extends _i1.Mock implements _i4.GetAllCategories {
  MockGetAllCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Category>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Category>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Category>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Category>>>);
}

/// A class which mocks [CreateCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCategory extends _i1.Mock implements _i8.CreateCategory {
  MockCreateCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Category>> call({
    required String? name,
    required List<String>? keywords,
    String? color,
    String? icon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #name: name,
            #keywords: keywords,
            #color: color,
            #icon: icon,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Category>>.value(
            _FakeEither_1<_i6.Failure, _i7.Category>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #name: name,
              #keywords: keywords,
              #color: color,
              #icon: icon,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Category>>);
}

/// A class which mocks [UpdateCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCategory extends _i1.Mock implements _i9.UpdateCategory {
  MockUpdateCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [category],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [category],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCategory extends _i1.Mock implements _i10.DeleteCategory {
  MockDeleteCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
