// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/history/presentation/bloc/history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interval/core/errors/failures.dart' as _i6;
import 'package:interval/features/logging/domain/entities/log.dart' as _i7;
import 'package:interval/features/logging/domain/repositories/log_repository.dart'
    as _i2;
import 'package:interval/features/logging/domain/usecases/get_logs_by_date_range.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogRepository_0 extends _i1.SmartFake implements _i2.LogRepository {
  _FakeLogRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetLogsByDateRange].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLogsByDateRange extends _i1.Mock
    implements _i4.GetLogsByDateRange {
  MockGetLogsByDateRange() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LogRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLogRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LogRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Log>>> call({
    required int? startTimestamp,
    required int? endTimestamp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #startTimestamp: startTimestamp,
            #endTimestamp: endTimestamp,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Log>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Log>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #startTimestamp: startTimestamp,
              #endTimestamp: endTimestamp,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Log>>>);
}
