// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/insights/domain/usecases/calculate_completion_rate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interval/core/errors/failures.dart' as _i5;
import 'package:interval/features/insights/domain/entities/insight.dart' as _i6;
import 'package:interval/features/insights/domain/repositories/insight_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InsightRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsightRepository extends _i1.Mock implements _i3.InsightRepository {
  MockInsightRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>> getInsightById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsightById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight>(
          this,
          Invocation.method(
            #getInsightById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>> getInsight({
    required String? insightType,
    required String? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsight,
          [],
          {
            #insightType: insightType,
            #date: date,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight?>(
          this,
          Invocation.method(
            #getInsight,
            [],
            {
              #insightType: insightType,
              #date: date,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>> getInsightsByType({
    required String? insightType,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsightsByType,
          [],
          {
            #insightType: insightType,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Insight>>(
          this,
          Invocation.method(
            #getInsightsByType,
            [],
            {
              #insightType: insightType,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>> getDailyInsights({
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyInsights,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Insight>>(
          this,
          Invocation.method(
            #getDailyInsights,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Insight>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>> getTodayInsight() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodayInsight,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight?>(
          this,
          Invocation.method(
            #getTodayInsight,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>> getWeeklyInsight() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyInsight,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight?>(
          this,
          Invocation.method(
            #getWeeklyInsight,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>> getMonthlyInsight() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyInsight,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight?>(
          this,
          Invocation.method(
            #getMonthlyInsight,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> upsertInsight({
    required String? id,
    required String? insightType,
    required String? date,
    required String? data,
    int? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertInsight,
          [],
          {
            #id: id,
            #insightType: insightType,
            #date: date,
            #data: data,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #upsertInsight,
            [],
            {
              #id: id,
              #insightType: insightType,
              #date: date,
              #data: data,
              #expiresAt: expiresAt,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>> generateDailyInsight(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateDailyInsight,
          [date],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>>.value(
            _FakeEither_0<_i5.Failure, _i6.Insight>(
          this,
          Invocation.method(
            #generateDailyInsight,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Insight>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteExpiredInsights() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpiredInsights,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteExpiredInsights,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteInsightsByType(
          String? insightType) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInsightsByType,
          [insightType],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteInsightsByType,
            [insightType],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getInsightsCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsightsCount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getInsightsCount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Insight>>> watchInsightsByType({
    required String? insightType,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchInsightsByType,
          [],
          {
            #insightType: insightType,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Insight>>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.Insight>>>);
}
