// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/notifications/domain/usecases/initialize_notifications_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:interval/core/errors/failures.dart' as _i5;
import 'package:interval/features/notifications/domain/entities/notification_action.dart'
    as _i7;
import 'package:interval/features/notifications/domain/entities/scheduled_notification.dart'
    as _i6;
import 'package:interval/features/notifications/domain/repositories/notification_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i3.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> requestPermissions() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #requestPermissions,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> areNotificationsEnabled() =>
      (super.noSuchMethod(
        Invocation.method(
          #areNotificationsEnabled,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #areNotificationsEnabled,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> scheduleIntervalNotification(
          _i6.ScheduleNotificationInput? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleIntervalNotification,
          [input],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #scheduleIntervalNotification,
            [input],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> scheduleRecurringNotifications(
    int? intervalDuration,
    int? count, {
    int? startHour = 9,
    int? endHour = 21,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleRecurringNotifications,
          [
            intervalDuration,
            count,
          ],
          {
            #startHour: startHour,
            #endHour: endHour,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #scheduleRecurringNotifications,
            [
              intervalDuration,
              count,
            ],
            {
              #startHour: startHour,
              #endHour: endHour,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, DateTime?>> getNextNotificationTime(
    int? intervalDuration,
    int? startHour,
    int? endHour,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextNotificationTime,
          [
            intervalDuration,
            startHour,
            endHour,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, DateTime?>>.value(
            _FakeEither_0<_i5.Failure, DateTime?>(
          this,
          Invocation.method(
            #getNextNotificationTime,
            [
              intervalDuration,
              startHour,
              endHour,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, DateTime?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelNotification(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelNotification,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelAllNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelAllNotifications,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ScheduledNotification>>>
      getPendingNotifications() => (super.noSuchMethod(
            Invocation.method(
              #getPendingNotifications,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i6.ScheduledNotification>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ScheduledNotification>>(
              this,
              Invocation.method(
                #getPendingNotifications,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.ScheduledNotification>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.NotificationAction?>>
      getLastNotificationAction() => (super.noSuchMethod(
            Invocation.method(
              #getLastNotificationAction,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i7.NotificationAction?>>.value(
                _FakeEither_0<_i5.Failure, _i7.NotificationAction?>(
              this,
              Invocation.method(
                #getLastNotificationAction,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.NotificationAction?>>);
}
