// Mocks generated by Mockito 5.4.4 from annotations
// in interval/test/features/notifications/presentation/bloc/notification_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:interval/core/errors/failures.dart' as _i7;
import 'package:interval/features/notifications/domain/entities/scheduled_notification.dart'
    as _i10;
import 'package:interval/features/notifications/domain/repositories/notification_repository.dart'
    as _i2;
import 'package:interval/features/notifications/domain/usecases/cancel_all_notifications.dart'
    as _i12;
import 'package:interval/features/notifications/domain/usecases/get_pending_notifications.dart'
    as _i13;
import 'package:interval/features/notifications/domain/usecases/initialize_notifications.dart'
    as _i5;
import 'package:interval/features/notifications/domain/usecases/request_notification_permissions.dart'
    as _i8;
import 'package:interval/features/notifications/domain/usecases/schedule_interval_notification.dart'
    as _i9;
import 'package:interval/features/notifications/domain/usecases/schedule_recurring_notifications.dart'
    as _i11;
import 'package:interval/features/settings/domain/entities/app_settings.dart'
    as _i15;
import 'package:interval/features/settings/domain/repositories/settings_repository.dart'
    as _i4;
import 'package:interval/features/settings/domain/usecases/get_app_settings.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationRepository_0 extends _i1.SmartFake
    implements _i2.NotificationRepository {
  _FakeNotificationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsRepository_2 extends _i1.SmartFake
    implements _i4.SettingsRepository {
  _FakeSettingsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InitializeNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializeNotifications extends _i1.Mock
    implements _i5.InitializeNotifications {
  MockInitializeNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, bool>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, bool>>.value(
            _FakeEither_1<_i7.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, bool>>);
}

/// A class which mocks [RequestNotificationPermissions].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestNotificationPermissions extends _i1.Mock
    implements _i8.RequestNotificationPermissions {
  MockRequestNotificationPermissions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, bool>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, bool>>.value(
            _FakeEither_1<_i7.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, bool>>);
}

/// A class which mocks [ScheduleIntervalNotification].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleIntervalNotification extends _i1.Mock
    implements _i9.ScheduleIntervalNotification {
  MockScheduleIntervalNotification() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(
          _i10.ScheduleNotificationInput? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [input],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
            _FakeEither_1<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [input],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [ScheduleRecurringNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleRecurringNotifications extends _i1.Mock
    implements _i11.ScheduleRecurringNotifications {
  MockScheduleRecurringNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(
    int? intervalDuration,
    int? count, {
    int? startHour = 9,
    int? endHour = 21,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            intervalDuration,
            count,
          ],
          {
            #startHour: startHour,
            #endHour: endHour,
          },
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
            _FakeEither_1<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [
              intervalDuration,
              count,
            ],
            {
              #startHour: startHour,
              #endHour: endHour,
            },
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [CancelAllNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelAllNotifications extends _i1.Mock
    implements _i12.CancelAllNotifications {
  MockCancelAllNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
            _FakeEither_1<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetPendingNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingNotifications extends _i1.Mock
    implements _i13.GetPendingNotifications {
  MockGetPendingNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i10.ScheduledNotification>>>
      call() => (super.noSuchMethod(
            Invocation.method(
              #call,
              [],
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure,
                        List<_i10.ScheduledNotification>>>.value(
                _FakeEither_1<_i7.Failure, List<_i10.ScheduledNotification>>(
              this,
              Invocation.method(
                #call,
                [],
              ),
            )),
          ) as _i6.Future<
              _i3.Either<_i7.Failure, List<_i10.ScheduledNotification>>>);
}

/// A class which mocks [GetAppSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppSettings extends _i1.Mock implements _i14.GetAppSettings {
  MockGetAppSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SettingsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSettingsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.SettingsRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i15.AppSettings>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i15.AppSettings>>.value(
                _FakeEither_1<_i7.Failure, _i15.AppSettings>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i15.AppSettings>>);
}
